# Generated by Django 5.1.3 on 2024-11-10 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_answer_user_alter_result_user'),
        ('user', '0002_user_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
